"""Modificar tabla personal, columna sector_id cambia a nulleable

Revision ID: 563a4af62d31
Revises: bcdc470b412a
Create Date: 2024-09-10 15:22:46.571444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '563a4af62d31'
down_revision = 'bcdc470b412a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.alter_column('sector_id_sector',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.alter_column('sector_id_sector',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
