"""Fecha de vencimiento pruba hidraulica nulleable true

Revision ID: 580b7b1ce3f0
Revises: 9ebac80edbb0
Create Date: 2024-10-15 12:47:16.516987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580b7b1ce3f0'
down_revision = '9ebac80edbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matafuegos', schema=None) as batch_op:
        batch_op.alter_column('fecha_vencimiento_prueba_hidraulica',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matafuegos', schema=None) as batch_op:
        batch_op.alter_column('fecha_vencimiento_prueba_hidraulica',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
