"""Modificacion estructura de herramientas a cargo

Revision ID: 6a16e894f307
Revises: 73fa833bec8f
Create Date: 2024-11-21 14:12:21.188914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a16e894f307'
down_revision = '73fa833bec8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devolucion_herramientas_a_cargo',
    sa.Column('id_registro_devolucion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_registro_entrega', sa.Integer(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('Sano', 'Roto', 'Perdido'), nullable=True),
    sa.Column('observacion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_registro_entrega'], ['herramientas_a_cargo.id_herramientas_a_cargo'], ),
    sa.PrimaryKeyConstraint('id_registro_devolucion')
    )
    with op.batch_alter_table('elementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))

    with op.batch_alter_table('herramientas_a_cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_entrega', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('herramienta', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('procedencia', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('observacion', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'personal', ['procedencia'], ['legajo_personal'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramientas_a_cargo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('observacion')
        batch_op.drop_column('procedencia')
        batch_op.drop_column('herramienta')
        batch_op.drop_column('fecha_entrega')

    with op.batch_alter_table('elementos', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    op.drop_table('devolucion_herramientas_a_cargo')
    # ### end Alembic commands ###
