"""Creada la estructura para las categorias y elementos del pañol

Revision ID: 73fa833bec8f
Revises: 580b7b1ce3f0
Create Date: 2024-11-07 15:08:18.828547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fa833bec8f'
down_revision = '580b7b1ce3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_padre', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categorias_inventario', ['id_padre'], ['id_categorias_inventario'])

    with op.batch_alter_table('elementos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))

    with op.batch_alter_table('herramientas_a_cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_entrega', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('herramienta', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramientas_a_cargo', schema=None) as batch_op:
        batch_op.drop_column('herramienta')
        batch_op.drop_column('fecha_entrega')

    with op.batch_alter_table('elementos', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    with op.batch_alter_table('categorias_inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_padre')

    # ### end Alembic commands ###
