"""Columna id_herramienta agregada a la tabla herramientas_a_cargo

Revision ID: 79b63bf61106
Revises: 6a16e894f307
Create Date: 2024-11-21 16:53:48.543661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b63bf61106'
down_revision = '6a16e894f307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramientas_a_cargo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_herramienta', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herramientas_a_cargo', schema=None) as batch_op:
        batch_op.drop_column('id_herramienta')

    # ### end Alembic commands ###
