from app import db
from .area import Area
from .categorias_inventario import CategoriasInventario
from .control_diario import ControlDiario
from .elementos_numerados import ElementosNumerados
from .elementos import Elementos
from .herramientas_cargo import HerramientasACargo
from .herramientas_prestamo import HerramientasAPrestamo
from .matafuegos_recarga import MatafuegosRecarga
from .matafuegos import Matafuegos
from .personal import Personal
from .sector import Sector
from .stock import Stock
from .talles_epp import TallesEpp
from .tipo_vestimenta import TipoVestimentaEpp